import Link from 'next/link'
import { BrandLogo } from '@/components/brand-logo'

type Role = 'admin' | 'teacher' | 'parent'
type PortalData = { title: string; desc: string; accent: string; links: [string, string][]; stats: [string, string][] }
const copy: Record<Role, PortalData> = {
  admin: { title: 'بوابة الإدارة', desc: 'مركز التحكم في المدرسة والقرارات اليومية', accent: 'بيانات المدرسة', links: [['الطلاب', 'إدارة الملفات والفصول'], ['المعلمون', 'الحسابات والتكليفات'], ['الفصول والمواد', 'بناء الهيكل الدراسي'], ['التقارير', 'الحضور والنتائج'],], stats: [['الطلاب', '—'], ['المعلمون', '—'], ['الفصول', '—']] },
  teacher: { title: 'بوابة المعلم', desc: 'مساحتك اليومية لإدارة التعلم', accent: 'مهامي اليوم', links: [['شعبي', 'الشعب المسندة إليك'], ['الحضور', 'تسجيل حضور الطلاب'], ['التقييمات', 'إدخال الدرجات والملاحظات'], ['التنبيهات', 'رسائل المدرسة'],], stats: [['حصص اليوم', '—'], ['تقييمات معلقة', '—'], ['غياب اليوم', '—']] },
  parent: { title: 'بوابة ولي الأمر', desc: 'متابعة أبنائك بوضوح واطمئنان', accent: 'ملخص الأبناء', links: [['أبنائي', 'ملفات الطلاب المرتبطين'], ['الأداء الدراسي', 'الدرجات ومتوسطات المواد'], ['الحضور', 'سجل الحضور والغياب'], ['التنبيهات', 'آخر أخبار المدرسة'],], stats: [['الأبناء', '—'], ['متوسط الأداء', '—'], ['الحضور', '—']] },
}
export function PortalPage({ role }: { role: Role }) { const data = copy[role]; return <main className="min-h-screen bg-background p-5 lg:p-10"><div className="mx-auto max-w-6xl"><header className="mb-8 flex items-center justify-between border-b border-border pb-6"><div><BrandLogo size={40} rounded="rounded-xl" /><h1 className="mt-3 text-3xl font-bold">{data.title}</h1><p className="mt-2 text-muted-foreground">{data.desc}</p></div><Link href={`/${role}/login`} className="rounded-xl border border-border px-4 py-2 text-sm font-semibold hover:bg-muted">تسجيل الخروج</Link></header><p className="mb-3 text-sm font-bold">{data.accent}</p><div className="mb-6 grid gap-4 sm:grid-cols-3">{data.stats.map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-muted-foreground">بانتظار ربط الحساب بالمدرسة</p></div>)}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{data.links.map(([title, desc]) => <section key={title} className="rounded-2xl border border-border bg-card p-5"><h2 className="font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p><button className="mt-8 w-full rounded-xl bg-muted py-2 text-sm font-semibold text-muted-foreground">فتح القسم</button></section>)}</div><section className="mt-6 rounded-2xl border border-dashed border-border p-8 text-center"><h2 className="font-bold">لا توجد بيانات مرتبطة بعد</h2><p className="mt-2 text-sm text-muted-foreground">هذه البوابة منفصلة عن البوابات الأخرى. ستظهر بيانات {role === 'parent' ? 'أبنائك' : 'مدرستك'} بعد تفعيل الحساب.</p></section></div></main> }
export function LoginPage({ role }: { role: Role }) { const data = copy[role]; return <main className="flex min-h-screen items-center justify-center bg-background p-5"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-7 shadow-sm"><Link href="/" className="text-sm font-bold text-primary">← العودة لاختيار البوابة</Link><h1 className="mt-10 text-3xl font-bold">{data.title}</h1><p className="mt-2 text-muted-foreground">سجّل الدخول للوصول إلى مساحتك الخاصة.</p><form className="mt-8 space-y-5"><label className="block text-sm font-semibold">{role === 'parent' ? 'رقم الجوال' : 'البريد الإلكتروني'}<input required className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" placeholder={role === 'parent' ? '05xxxxxxxx' : 'name@school.sa'} /></label><label className="block text-sm font-semibold">كلمة المرور<input required type="password" className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" /></label><Link href={`/${role}`} className="block rounded-xl bg-primary py-3 text-center text-sm font-bold text-primary-foreground">دخول إلى البوابة</Link></form><p className="mt-6 text-center text-xs leading-5 text-muted-foreground">الوصول الفعلي والصلاحيات يحتاجان تفعيل مفتاح Better Auth.</p></div></main> }
